### ISSUE TITLE
Rails example's full build script link is 404-ing

### ISSUE THREAD

**Issue by ianbayne** [benpickles/parklife#90]
This looks like a great project! Unfortunately, the [Rails example's full build script](https://github.com/benpickles/parklife/blob/main/examples/rails/parklife-build) linked to in the README is 404-ing.

**Comment by Spone** [comment]
I guess this is the correct link: https://github.com/benpickles/parklife/blob/main/examples/rails/bin/static-build

**Comment by ianbayne** [comment]
> I guess this is the correct link: https://github.com/benpickles/parklife/blob/main/examples/rails/bin/static-build

Thank you!
